# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Sentinel
                                 A QGIS plugin
 Faz o download de acordo com as bandas selecionadas do satelite Sentinel 2 MSI_SR
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-07-07
        copyright            : (C) 2021 by Luiz Zampronio
        email                : lpzampronio@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Sentinel class from file Sentinel.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sentinel import Sentinel
    return Sentinel(iface)
